"""empty message

Revision ID: 1725acab0205
Revises: b56bcaf2f17a
Create Date: 2021-05-26 20:33:01.193287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1725acab0205'
down_revision = 'b56bcaf2f17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=False),
    sa.Column('expiring', sa.DateTime(), nullable=True),
    sa.Column('ended', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['storage_slot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_expiring'), 'storage', ['expiring'], unique=False)
    op.create_index(op.f('ix_storage_user_id'), 'storage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_user_id'), table_name='storage')
    op.drop_index(op.f('ix_storage_expiring'), table_name='storage')
    op.drop_table('storage')
    # ### end Alembic commands ###
