version: '3'
services: 
    api:
        build: app/backend/.
        ports:
        - "8080:8000"
        volumes:
        - ./app/backend:/usr/src/app
        depends_on:
        - "db"
        networks:
            main:
                aliases:
                    - api
    db:
        hostname: db
        restart: always
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'example'
            MYSQL_DATABASE: 'dms-storage'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        volumes:
            - ./.data:/var/lib/mysql
            #- SYS_NICE  # CAP_SYS_NICE
        ports:
        - "6666:3306"
        networks:
            main:
                aliases:
                    - db
    frontend:
        hostname: ui
        build: app/frontend/.
        volumes:
        - ./app/frontend:/usr/src/app
        ports:
        - 4200:4200
        command: >
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --poll 500"
        networks:
            main:
                aliases:
                    - ui
        depends_on: 
        - "api"
    openldap:
        extends:
            file: ./dms-ad-openldap/docker-compose.yml
            service: openldap
            #container_name: openldap
        networks:
            main:
                aliases:
                    - openldap
    phpldapadmin:
        extends:
            file: ./dms-ad-openldap/docker-compose.yml
            service: phpldapadmin
            #container_name: phpldapadmin
        networks:
            main:
                aliases:
                    - phpldapadmin
        depends_on: 
        - openldap
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
        - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
        - 8081:80
networks:
    main: