version: '3'
services: 
    api:
        build: app/backend/.
        ports:
        - "8080:8000"
        #volumes:
        #- ./app:/usr/src/app
        depends_on:
        - "db"
        networks:
            main:
                aliases:
                    - api
    db:
        hostname: db
        restart: always
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'example'
            MYSQL_DATABASE: 'dms-storage'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        volumes:
            - ./.data:/var/lib/mysql
            #- SYS_NICE  # CAP_SYS_NICE
        ports:
        - "6666:3306"
        networks:
            main:
                aliases:
                    - db

volumes:
    web-data:
networks:
    main: