version: '3'
services: 
    api:
        build: app/.
        ports:
        - "8080:5000"
        volumes:
        - ./app:/usr/src/app
        depends_on:
        - "db"
        networks:
            main:
                aliases:
                    - api
    db:
        hostname: db
        restart: always
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - ./.data:/var/lib/mysql
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        ports:
        - "3306:3306"
        networks:
            main:
                aliases:
                    - db

volumes:
    web-data:
networks:
    main: